;; auto-complete の設定
(require 'auto-complete-config)
(global-auto-complete-mode 1)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/elpa/auto-complete/dict/")
(add-to-list 'ac-sources 'ac-source-yasnippet)
(define-key ac-mode-map (kbd "C-t") 'auto-complete)
(ac-config-default)
(setq ac-auto-start 1)
(setq ac-auto-show-menu 0.05)
(setq ac-dwim t)
(setq ac-use-comphist t)
(setq ac-candidate-limit nil)
(setq ac-use-menu-map t)
(setq ac-menu-height 20)
(setq ac-ignore-case t)
(define-key ac-completing-map (kbd "C-p") 'ac-previous)
(define-key ac-completing-map (kbd "C-n") 'ac-next)
(set-face-background 'ac-candidate-face "red")
(set-face-background 'ac-selection-face "blue")
(setq ac-comphist-file "~/.emacs.d/elpa/auto-complete/ac-comphist.dat")
